services:
  ollama-llm:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"

  db:
    image: pgvector/pgvector:pg17
    ports:
      - "5432:5432"
    environment:
      - PGUSER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres

  prepare-models:
    image: ollama/ollama:latest
    depends_on:
      - ollama-llm
    environment:
      - OLLAMA_HOST=http://ollama-llm:11434
    entrypoint: >
      sh -c "
        echo 'Waiting for Ollama server to start...' &&
        sleep 10 &&
        echo 'Pulling  mxbai-embed-large  ...' &&
        ollama pull mxbai-embed-large  &&
        echo 'Model preparation complete.'"